### ISSUE TITLE
About Vit-VQGAN

### ISSUE THREAD

**Issue by thuangb** [lucidrains/parti-pytorch#1]
Hi @lucidrains, if you dont mind, can you change the README a bit? Your ViT-VQGAN implementation is certainly not the only public one as I have already implemented ViT-VQGAN months ago in [here](https://github.com/thuangb/enhancing-transformers)

**Comment by lucidrains** [comment]
@thuangb oh yes indeed! my bad 😄 https://github.com/lucidrains/parti-pytorch/commit/f0f0b7a39b00f2c5284fd302e902c36768e6e68f

**Comment by thuangb** [comment]
Thank you 😄
