### ISSUE TITLE
About the size of dimension , the code broke down...

### ISSUE THREAD

**Issue by alice-cool** [lucidrains/parti-pytorch#3]
Dear scholar,

When the size of dimension is 256, the code broke down  and I try to change the size of dimension to 64 (it is from [3，16，16，512，64]), the code broke down again. Could you help me? I hope for your reply.

![3e9246057db6b0336ae6e2204c85474](https://user-images.githubusercontent.com/16870890/183322563-39ba3a1e-0047-485c-a0a2-2c3a54d101db.jpg)

**Comment by lucidrains** [comment]
@alice-cool could you send me the script you are running?

**Comment by lucidrains** [comment]
@alice-cool oh apologies, i broke it with a recent change to a dependent library

should be fixed now! https://github.com/lucidrains/parti-pytorch/commit/c8ad99d0b0a0b42c7172ba954c0961fbbc2b0790

**Comment by lucidrains** [comment]
@alice-cool are you training this?

**Comment by alice-cool** [comment]
> @alice-cool are you training this?
Thanks for your timely reply, I will try it now.

**Comment by snarb** [comment]
@lucidrains  I have try to run training with 32 *32 images (random crops of one big image).  I I had to reduce number of discriminator layers from 4 to 3 to avoid too small tensor in the end.
After night of training on A100 I get blurred results ( grad_accum_every = 1,  batch_size = 4 * 8 * 10, other default)
Looks like something is wrong with training. It even can't overfit well. 
![58000](https://user-images.githubusercontent.com/4518007/183351612-c592ce7e-cf61-4c91-b564-fe4f5396e7ff.png)

**Comment by alice-cool** [comment]
> @alice-cool are you training this?

Thanks for your timely reply. When I download the newest version from your github, I again meet some errors.  The code broke down  in the second phrase(generating image section)
![ca3a1b2d7496b9cf39fe0f19bf1789a](https://user-images.githubusercontent.com/16870890/183356535-e693cbf0-078b-4a26-a8e8-c287fbca6d79.jpg)

I guess maybe the codebook cause this error. When the image tokens (the shape is [3,16,16]) is passed into  "codebook",  it will output the shape of [3,16,16,512,64]. Do you think the step cause the error?

**Comment by lucidrains** [comment]
@alice-cool try running `pip install parti-pytorch==0.0.16` first

**Comment by alice-cool** [comment]
> @alice-cool try running `pip install parti-pytorch==0.0.16` first

Thanks. It helps me a lot. Thanks
